/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cateringreservationsystem;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.awt.HeadlessException;
import java.awt.event.KeyEvent;
import java.sql.DriverManager;
import java.sql.SQLException;
import javax.swing.JOptionPane;

public class SignUpForm extends javax.swing.JFrame {

    public Connection con;
    public Statement state;
    public String sql;
    
    public SignUpForm() {
        initComponents();
        
        
        WarnCell.setVisible(false);
        WarnF.setVisible(false);
        WarnL.setVisible(false);
        WarnS.setVisible(false);
        WarnP.setVisible(false);
        WarnB.setVisible(false);
        
        
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/cateringsystem?zeroDateTimeBehavior=convertToNull","root", "");
            state = (Statement) con.createStatement();
        }
        catch(ClassNotFoundException | SQLException c)
        {
            JOptionPane.showMessageDialog(null, c);
        }
        /*try
        {
            Class.forName("com.mysql.jdbc.Driver");
            con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/cateringreservationsystem?zeroDateTimeBehavior=convertToNull","root", "");
            state = (Statement) con.createStatement();
            
        }
        catch(ClassNotFoundException | SQLException c)
        {
            JOptionPane.showMessageDialog(null, c);
        }*/
        
       
    }
    
     public void addMember()
        {
            try
            {
                //sql ="INSERT INTO `users` (`First_Name`,`Last_Name`,`Sex`,`cellNo`,`Purok`,`Barangay`) VALUES("+fname.getText()+" , "+lname.getText()+" , "+sex.getSelection().getActionCommand()+" , "+cellNo.getText()+" , "+purok.getText()+" , "+brgy.getText()+")";
                sql = "INSERT INTO `users`(`Name`,`Sex`,`cellNo`,`Purok`,`Barangay`) VALUES ("+"\"" + fname.getText() + " " + lname.getText() + "\""+", "+"\"" + sex.getSelection().getActionCommand()+ "\""+","+"\"" + cellNo.getText()+ "\""+", "+"\"" + purok.getText()+ "\""+", "+"\"" + brgy.getText()+ "\""+")";
               //sql = "INSERT INTO `reservation`(`Name`) VALUES("+"\"" + fname.getText() + " " + lname.getText() + "\""+")";
                state.execute(sql);
                JOptionPane.showMessageDialog(null, "Saved");
            }
            catch(SQLException | HeadlessException c)
            {
                JOptionPane.showMessageDialog(null, c ,"", JOptionPane.ERROR_MESSAGE);
            }
            
            /*try
            {
                sql ="INSERT INTO `members`(`First Name`,`Last Name`,`Sex`,`Cellphone No.`,`Street/Purok`,`Barangay`) VALUES (`"+ fname.getText() + "','" + lname.getText() + "','" + sex.getSelection().getActionCommand() + "','" + cellNo.getText() + "','" + purok.getText() + "','" + brgy.getText() +"')";
                state.executeUpdate(sql);
                JOptionPane.showMessageDialog(null, "Saved");
                fname.setText("");
                lname.setText("");
            }
            catch(SQLException | HeadlessException c)
            {
                JOptionPane.showMessageDialog(null, c ,"", JOptionPane.ERROR_MESSAGE);
            }*/
            
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sex = new javax.swing.ButtonGroup();
        SignUpPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        fname = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        lname = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        male = new javax.swing.JRadioButton();
        female = new javax.swing.JRadioButton();
        jLabel14 = new javax.swing.JLabel();
        cellNo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        purok = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        brgy = new javax.swing.JTextField();
        signUp = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        WarnCell = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        WarnF = new javax.swing.JLabel();
        WarnL = new javax.swing.JLabel();
        WarnP = new javax.swing.JLabel();
        WarnB = new javax.swing.JLabel();
        WarnS = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        SignUpPanel.setBackground(new java.awt.Color(255, 153, 153));

        jLabel1.setText("First name");

        fname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnameActionPerformed(evt);
            }
        });
        fname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fnameKeyTyped(evt);
            }
        });

        jLabel2.setText("Last name");

        lname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                lnameKeyTyped(evt);
            }
        });

        jLabel6.setText("Sex");

        sex.add(male);
        male.setText("Male");

        sex.add(female);
        female.setText("Female");

        jLabel14.setText("Cellphone no.");

        cellNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cellNoActionPerformed(evt);
            }
        });
        cellNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cellNoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cellNoKeyTyped(evt);
            }
        });

        jLabel3.setText("Street/Purok");

        purok.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                purokKeyTyped(evt);
            }
        });

        jLabel4.setText("Barangay");

        brgy.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                brgyKeyTyped(evt);
            }
        });

        signUp.setText("Sign Up");
        signUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signUpActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Rockwell Condensed", 2, 36)); // NOI18N
        jLabel5.setText("SIGN UP FORM");

        WarnCell.setForeground(java.awt.Color.red);
        WarnCell.setText("invalid");

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        WarnF.setForeground(java.awt.Color.red);
        WarnF.setText("invalid");

        WarnL.setForeground(java.awt.Color.red);
        WarnL.setText("invalid");

        WarnP.setForeground(java.awt.Color.red);
        WarnP.setText("invalid");

        WarnB.setForeground(java.awt.Color.red);
        WarnB.setText("invalid");

        WarnS.setForeground(java.awt.Color.red);
        WarnS.setText("Please choose");

        javax.swing.GroupLayout SignUpPanelLayout = new javax.swing.GroupLayout(SignUpPanel);
        SignUpPanel.setLayout(SignUpPanelLayout);
        SignUpPanelLayout.setHorizontalGroup(
            SignUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SignUpPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SignUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SignUpPanelLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(lname, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(WarnL))
                    .addComponent(jLabel2)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(SignUpPanelLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(fname, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(WarnF))
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addGroup(SignUpPanelLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(purok, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(WarnP))
                    .addGroup(SignUpPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(male)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(female)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(WarnS))
                    .addGroup(SignUpPanelLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(cellNo, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(WarnCell))
                    .addComponent(jLabel14)
                    .addGroup(SignUpPanelLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(brgy, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(WarnB))
                    .addComponent(jLabel4)
                    .addGroup(SignUpPanelLayout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(signUp, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(SignUpPanelLayout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(jButton1))
                    .addComponent(jLabel6))
                .addContainerGap(7, Short.MAX_VALUE))
        );
        SignUpPanelLayout.setVerticalGroup(
            SignUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SignUpPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(2, 2, 2)
                .addGroup(SignUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(WarnF))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(SignUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(WarnL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SignUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SignUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(female)
                        .addComponent(WarnS))
                    .addComponent(male))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SignUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cellNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(WarnCell))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SignUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(purok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(WarnP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SignUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(brgy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(WarnB))
                .addGap(32, 32, 32)
                .addComponent(signUp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(140, 140, 140))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SignUpPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SignUpPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 510, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cellNoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cellNoKeyTyped
        //String cNo = cellNo.getText().trim();
        char cell = evt.getKeyChar();
        if(!(Character.isDigit(cell)) || (cell == KeyEvent.VK_BACK_SPACE) || (cell == KeyEvent.VK_DELETE))
                {
                    evt.consume();
                }
        
    }//GEN-LAST:event_cellNoKeyTyped

    private void fnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fnameKeyTyped
       char first = evt.getKeyChar();
       //String fn = fname.getText().replaceAll("[0-9^\\w&&( )+","").trim();
        if((Character.isDigit(first)) || (evt.isAltDown()) || first == KeyEvent.VK_DELETE || first == KeyEvent.VK_BACK_SPACE)
        {
            evt.consume();
        }
        
    }//GEN-LAST:event_fnameKeyTyped

    private void lnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lnameKeyTyped
        char last = evt.getKeyChar();
        if((Character.isDigit(last)) || (evt.isAltDown()) || last == KeyEvent.VK_DELETE || last == KeyEvent.VK_BACK_SPACE)
        {
            evt.consume();
        }
    }//GEN-LAST:event_lnameKeyTyped

    private void brgyKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_brgyKeyTyped
        char barangay = evt.getKeyChar();
        if((Character.isDigit(barangay)) || (evt.isAltDown()) || barangay == KeyEvent.VK_DELETE || barangay == KeyEvent.VK_BACK_SPACE)
        {
            evt.consume();
        }
    }//GEN-LAST:event_brgyKeyTyped

    private void purokKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_purokKeyTyped
   
    }//GEN-LAST:event_purokKeyTyped

    private void signUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signUpActionPerformed
        cellNo.setEditable(true);
        String fn = fname.getText().replaceAll("[^0-9|^\\w|( )+|^ +| +$]","").trim();
        String ln = lname.getText().replaceAll("[^0-9|^\\w|( )+|^ +| +$]","").trim();
        String cNo = cellNo.getText().replaceAll("[^\\w|( )+|^ +| +$]","").trim();
        String prok = purok.getText().replaceAll("([( )+|^ +| +$])([-])([,])","").trim();
        String brg = brgy.getText().replaceAll("([( )+|^ +| +$])([-])([,])","").trim();

        male.setActionCommand("Male");
        female.setActionCommand("Female");
        String SeX = sex.getSelection().getActionCommand();
        if(fn.isEmpty() || fn.length() == 1)
        {
            WarnF.setVisible(true);
        }
        else
        {
            WarnF.setVisible(false);
        }
        if(ln.isEmpty() || ln.length() == 1)
        {
            WarnL.setVisible(true);
        }
        else
        {
            WarnL.setVisible(false);
        }
        if(prok.isEmpty() || prok.length() == 1 )
        {
            WarnP.setVisible(true);
        }
        else
        {
            WarnP.setVisible(false);
        }
        if(brg.isEmpty() || brg.length() == 1)
        {
            WarnB.setVisible(true);
        }
        else
        {
            WarnB.setVisible(false);
        }
        if(sex.isSelected(null))
        {
            WarnS.setVisible(true);
        }
        else
        {
            WarnS.setVisible(false);
        }
        
        if(cNo.startsWith("09") && cNo.length() == 11)
        {
            WarnCell.setVisible(false);
                            
            if(fn.isEmpty() || fn.length() == 1 || ln.isEmpty() || ln.length() == 1 || cNo.isEmpty() || prok.isEmpty() || brg.isEmpty() || sex.isSelected(null))
            {    
                JOptionPane.showMessageDialog(this, "Please fill all Fields");    
            }
            else if(fn.length() > 1 || ln.length() > 1 || !WarnCell.isVisible() || !prok.isEmpty() || !brg.isEmpty() || !sex.isSelected(null))
            {    
                JOptionPane.showMessageDialog(this,"First Name: " + fname.getText() + "\n Last Name: " + lname.getText() + "\n Sex: " + sex.getSelection().getActionCommand() + "\n Cellphone #: "+ cNo +"\n Purok/Street: " + prok + "\n Barangay: " + brg,"",JOptionPane.PLAIN_MESSAGE);
                addMember();
                UserLogForm userLog = new UserLogForm();
                userLog.setVisible(true);
                this.dispose();
                }                
        }
        else
        {
            WarnCell.setVisible(true);
            
            if(WarnCell.isVisible())
            {
            JOptionPane.showMessageDialog(this, "Please comply");
            }
        }       
                  
                        
                        
                            
                        
                    
                    
         /*if(fn.isEmpty() || fn.length() == 1 || ln.isEmpty() || ln.length() == 1 || cNo.isEmpty() || prok.isEmpty() || brg.isEmpty() || sex.isSelected(null))
                    {    
                        JOptionPane.showMessageDialog(this, "Please fill all Fields");    
                    }
                    else if(fn.length() > 1 || ln.length() > 1 || !WarnCell.isVisible() || !prok.isEmpty() || !brg.isEmpty() || !sex.isSelected(null))
                    {    
                        JOptionPane.showMessageDialog(this,"First Name: " + fn + "\n Last Name: " + ln + "\n Sex: " + sex.getSelection().getActionCommand() + "\n Cellphone #: "+ cNo +"\n Purok/Street: " + prok + "\n Barangay: " + brg,"",JOptionPane.PLAIN_MESSAGE);
                        this.dispose();
                        new UserLogForm(fn,ln).setVisible(true);
                    }*/
            
    }//GEN-LAST:event_signUpActionPerformed

    private void fnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnameActionPerformed

    }//GEN-LAST:event_fnameActionPerformed

    private void cellNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cellNoActionPerformed
        
    }//GEN-LAST:event_cellNoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        UserLogForm uLform = new UserLogForm();
        uLform.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cellNoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cellNoKeyPressed
        int i = cellNo.getText().length();
        char c = evt.getKeyChar();
        
        
           
                if(evt.getExtendedKeyCode() == KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode() == KeyEvent.VK_DELETE)
                {
                    cellNo.setEditable(true);
                }
                else if(i>10)
                {
                    cellNo.setEditable(false);
                }
            
        
    }//GEN-LAST:event_cellNoKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUpForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUpForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUpForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUpForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUpForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel SignUpPanel;
    private javax.swing.JLabel WarnB;
    private javax.swing.JLabel WarnCell;
    private javax.swing.JLabel WarnF;
    private javax.swing.JLabel WarnL;
    private javax.swing.JLabel WarnP;
    private javax.swing.JLabel WarnS;
    private javax.swing.JTextField brgy;
    private javax.swing.JTextField cellNo;
    private javax.swing.JRadioButton female;
    private javax.swing.JTextField fname;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField lname;
    private javax.swing.JRadioButton male;
    private javax.swing.JTextField purok;
    private javax.swing.ButtonGroup sex;
    private javax.swing.JButton signUp;
    // End of variables declaration//GEN-END:variables
}
